In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import scipy.stats as st

rawdata = "Sources/FY22 Fundraising Data - Sheet1, 09.05.21.csv"
donation_data = pd.read_csv(rawdata)
donation_data

,Campaign Name,Bucket,Income FY22 (thru6/30/21),In-Kind Donations FY22,Volunteer Hours FY22,Intern Hours FY22,Expenses FY22,Income FY21,In-Kind Donations FY21,Volunteer Hours FY21,Expenses FY21
0,#StarfishSearch,1: Individual Giving,NaN,NaN,NaN,NaN,NaN,"$1,037.00",$0.00,15,$95.00
1,AEFTS - Auction,1: Individual Giving,"$4,984.83","$6,379.49",194,NaN,$670.00,"$9,808.13","$9,243.06",152,$803.34
2,AEFTS - Donations,1: Individual Giving,"$15,256.52",$0.00,70,NaN,$425.00,"$8,250.40",$0.00,0,$583.33
3,AEFTS - Tickets,1: Individual Giving,"$3,493.38",$349.14,133,NaN,$470.00,"$4,817.12",$384.79,538,$583.33
4,Birthday Campaigns,1: Individual Giving,"$1,020.00",$0.00,0,NaN,$0.00,"$4,159.77",$0.00,3,$0.00
5,Connections - Auction,1: Individual Giving,NaN,NaN,NaN,NaN,$300.00,$0.00,$0.00,0,$0.00
6,Connections - Donations,1: Individual Giving,NaN,NaN,NaN,NaN,$225.00,"$5,402.80","$1,774.46",222,$249.99
7,Connections - Tickets,1: Individual Giving,NaN,NaN,2,NaN,$155.00,$0.00,$0.00,0,$0.00
8,DM Round 1 - June Appeal,1: Individual Giving,"$4,006.51",$0.00,51,NaN,$314.88,"$5,525.97",$0.00,27,$210.06
9,DM Round 2 - Year End,1: Individual Giving,NaN,NaN,NaN,NaN,NaN,"$10,417.13",$283.65,35,$0.00
10,FUNd-a-thon,1: Individual Giving,NaN,NaN,NaN,NaN,NaN,"$3,724.12",$0.00,50,$0.00
11,Giving Tuesday,1: Individual Giving,NaN,NaN,NaN,NaN,NaN,"$7,332.46",$0.00,25,$0.00
12,Other Event / Other Fundraiser,1: Individual Giving,NaN,NaN,NaN,NaN,NaN,$309.30,$0.00,0,$0.00
13,Recurring Giving,1: Individual Giving,$565.00,$0.00,0,NaN,$0.00,$0.00,$0.00,0,$0.00
14,Sponsor a Scholar,1: Individual Giving,"$23,834.32",$0.00,39,NaN,$0.00,"$23,812.68",$0.00,60,$0.00
15,Starfish Bracket Challenge,1: Individual Giving,"$1,044.50",$160.00,74,NaN,$201.35,$0.00,$0.00,0,$175.00
16,Unsolicited Gifts,1: Individual Giving,$801.00,$0.00,0,NaN,$0.00,"$7,377.92",$0.00,3,$0.00
17,AEFTS - Sponsorships (1),2: Major Donors,"$29,313.73",$0.00,20,NaN,NaN,"$50,000.00",$0.00,57,$0.00
18,Major Gifts,2: Major Donors,"$3,000.00",$0.00,10,NaN,$0.00,"$34,475.00",$0.00,0,$0.00
19,University Efforts,2: Major Donors,$871.81,$0.00,20,NaN,$0.00,$0.00,$0.00,1,$0.00
20,Grant,3: Grants,$0.00,$0.00,46,NaN,NaN,"$8,750.00",$0.00,91,$0.00
21,Matching Grant,4: Corporations,"$1,875.85",$0.00,2,NaN,$0.00,"$22,329.48",$0.00,6,$0.00
22,AEFTS - Sponsorships (2),4: Corporations,"$2,036.27",$0.00,1,NaN,NaN,$520.56,$0.00,1,$0.00
23,AEFTS - Sales,5: Earned Revenue,$615.97,$0.00,10,NaN,NaN,$601.06,$704.94,11,$0.00
24,Amazon Smile and Other,5: Earned Revenue,$82.66,$0.00,0,NaN,$0.00,$310.16,$0.00,1,$0.00
25,CEA Vols,5: Earned Revenue,NaN,NaN,NaN,NaN,NaN,$0.00,$0.00,0,$0.00
26,Connections - Sales,5: Earned Revenue,NaN,NaN,NaN,NaN,NaN,$0.00,$0.00,0,$0.00
27,Friends of Starfish Trip,5: Earned Revenue,$0.00,$0.00,0,0,$0.00,$0.00,$0.00,0,$0.00
28,Starfish Shop,5: Earned Revenue,$296.03,$0.00,1,20,$0.00,$589.60,$284.25,29,$0.00
29,Volunteer Housing & Fundraisers,5: Earned Revenue,$0.00,$0.00,0,0,$0.00,$0.00,$0.00,0,$0.00
30,Restricted,NaN,NaN,NaN,NaN,NaN,NaN,"$1,000.00",$0.00,0,$0.00
31,NaN,NaN,"$93,098.38","$6,888.63",673.00,20.00,"$2,761.23","$210,550.66","$12,675.15","1,327.00","$2,700.05"
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Other fundraising expenses or in-kind donation...,NaN,-,$95.97,-,-,$0.00,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,received FY22,April 22 dinner,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,April 21 dinner,"$22,638.36","$5,966.99",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
FY22 = donation_data
FY22.replace(regex=['coming soon'], value=0, inplace=True)
FY22 = FY22.iloc[:31,:]
# FY21_FY20.replace(regex=['coming soon'], value=np.nan, inplace=True)
# FY21_FY20.dropna(inplace=True)
FY22[FY22.columns[2:]] = FY22[FY22.columns[2:]].replace('[\$,]', '', regex=True).astype(float)

FY22.to_csv("./ExcelOutputs/FY22_clean_campaign_data.csv", encoding="utf-8", index=True)
FY22

,Campaign Name,Bucket,Income FY22 (thru6/30/21),In-Kind Donations FY22,Volunteer Hours FY22,Intern Hours FY22,Expenses FY22,Income FY21,In-Kind Donations FY21,Volunteer Hours FY21,Expenses FY21
0,#StarfishSearch,1: Individual Giving,NaN,NaN,NaN,NaN,NaN,1037.00,0.00,15.0,95.00
1,AEFTS - Auction,1: Individual Giving,4984.83,6379.49,194.0,NaN,670.00,9808.13,9243.06,152.0,803.34
2,AEFTS - Donations,1: Individual Giving,15256.52,0.00,70.0,NaN,425.00,8250.40,0.00,0.0,583.33
3,AEFTS - Tickets,1: Individual Giving,3493.38,349.14,133.0,NaN,470.00,4817.12,384.79,538.0,583.33
4,Birthday Campaigns,1: Individual Giving,1020.00,0.00,0.0,NaN,0.00,4159.77,0.00,3.0,0.00
5,Connections - Auction,1: Individual Giving,NaN,NaN,NaN,NaN,300.00,0.00,0.00,0.0,0.00
6,Connections - Donations,1: Individual Giving,NaN,NaN,NaN,NaN,225.00,5402.80,1774.46,222.0,249.99
7,Connections - Tickets,1: Individual Giving,NaN,NaN,2.0,NaN,155.00,0.00,0.00,0.0,0.00
8,DM Round 1 - June Appeal,1: Individual Giving,4006.51,0.00,51.0,NaN,314.88,5525.97,0.00,27.0,210.06
9,DM Round 2 - Year End,1: Individual Giving,NaN,NaN,NaN,NaN,NaN,10417.13,283.65,35.0,0.00
10,FUNd-a-thon,1: Individual Giving,NaN,NaN,NaN,NaN,NaN,3724.12,0.00,50.0,0.00
11,Giving Tuesday,1: Individual Giving,NaN,NaN,NaN,NaN,NaN,7332.46,0.00,25.0,0.00
12,Other Event / Other Fundraiser,1: Individual Giving,NaN,NaN,NaN,NaN,NaN,309.30,0.00,0.0,0.00
13,Recurring Giving,1: Individual Giving,565.00,0.00,0.0,NaN,0.00,0.00,0.00,0.0,0.00
14,Sponsor a Scholar,1: Individual Giving,23834.32,0.00,39.0,NaN,0.00,23812.68,0.00,60.0,0.00
15,Starfish Bracket Challenge,1: Individual Giving,1044.50,160.00,74.0,NaN,201.35,0.00,0.00,0.0,175.00
16,Unsolicited Gifts,1: Individual Giving,801.00,0.00,0.0,NaN,0.00,7377.92,0.00,3.0,0.00
17,AEFTS - Sponsorships (1),2: Major Donors,29313.73,0.00,20.0,NaN,NaN,50000.00,0.00,57.0,0.00
18,Major Gifts,2: Major Donors,3000.00,0.00,10.0,NaN,0.00,34475.00,0.00,0.0,0.00
19,University Efforts,2: Major Donors,871.81,0.00,20.0,NaN,0.00,0.00,0.00,1.0,0.00
20,Grant,3: Grants,0.00,0.00,46.0,NaN,NaN,8750.00,0.00,91.0,0.00
21,Matching Grant,4: Corporations,1875.85,0.00,2.0,NaN,0.00,22329.48,0.00,6.0,0.00
22,AEFTS - Sponsorships (2),4: Corporations,2036.27,0.00,1.0,NaN,NaN,520.56,0.00,1.0,0.00
23,AEFTS - Sales,5: Earned Revenue,615.97,0.00,10.0,NaN,NaN,601.06,704.94,11.0,0.00
24,Amazon Smile and Other,5: Earned Revenue,82.66,0.00,0.0,NaN,0.00,310.16,0.00,1.0,0.00
25,CEA Vols,5: Earned Revenue,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.0,0.00
26,Connections - Sales,5: Earned Revenue,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.0,0.00
27,Friends of Starfish Trip,5: Earned Revenue,0.00,0.00,0.0,0.0,0.00,0.00,0.00,0.0,0.00
28,Starfish Shop,5: Earned Revenue,296.03,0.00,1.0,20.0,0.00,589.60,284.25,29.0,0.00
29,Volunteer Housing & Fundraisers,5: Earned Revenue,0.00,0.00,0.0,0.0,0.00,0.00,0.00,0.0,0.00
30,Restricted,NaN,NaN,NaN,NaN,NaN,NaN,1000.00,0.00,0.0,0.00