In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import scipy.stats as st

step2 = "Fundraising Strategy - Step 2, 08.07.20.csv"
donation_data = pd.read_csv(step2)
donation_data.head()

,Campaign Name,Bucket,Income FY21,In-Kind Donations FY21,Volunteer Hours FY21,Income FY20,In-Kind Donations FY20,Volunteer Hours FY20
0,Sponsor a Scholar,1: Individual Giving,"$12,420.45",$0.00,30,"$25,213.95",$0.00,75.0
1,Sponsor a Scholar - Fund a Thon,1: Individual Giving,coming soon,$0.00,coming soon,"$3,610.00",$3.50,20.0
2,Appeal - June,1: Individual Giving,"$9,641.00",$0.00,27,"$25,295.00",$341.23,20.0
3,Appeal - December,1: Individual Giving,coming soon,$0.00,coming soon,"$9,637.11",$459.55,20.0
4,Online appeal - Giving Tuesday,1: Individual Giving,coming soon,$0.00,coming soon,"$8,544.94","$1,499.08",36.0

In [14]:
# donation_data[donation_data.columns[2:7]] = donation_data[donation_data.columns[2:7]].replace('[\$,]', '', regex=True).astype(float)
# donation_data

In [20]:
expenses_import = "Advancement Calendar - FY21 calendar, 08.08.20.csv"
expenses_data = pd.read_csv(expenses_import)
expenses = expenses_data[['Event', 'Expenses FY21', 'Expenses FY20', 'Funds Raised FY20']]

expenses = expenses.rename(columns={"Event": "Campaign Name"})
expenses

,Campaign Name,Expenses FY21,Expenses FY20,Funds Raised FY20
0,Benefit Dinner (occuring April 2020) (SPANS TW...,$250.00,"$3,220.00","$65,987.57"
1,Sponsor a Scholar - Fund a Thon,$0.00,$0.00,"$3,610.00"
2,Appeal - June,$210.06,$0.00,"$25,295.00"
3,Ecua vols/visitors,$0.00,$25.00,"$5,487.46"
4,Online event - Starfish Search,$0.00,$302.00,"$1,268.00"
5,Thank-a-thon,$0.00,$386.63,--
6,4th quarter press,--,--,--
7,Appeal - December,$0.00,$224.92,"$9,637.11"
8,Online appeal - Giving Tuesday,$0.00,$25.50,"$8,544.94"
9,Lapsed Donors,$0.00,$0.00,$400.00
10,Online event - Starfish Bracket Challenge,$175.00,$0.00,"$1,115.00"
11,Sponsor a Scholar,$0.00,$0.00,"$25,213.95"
12,Benefit Dinner (occurring in April 2021) (SPAN...,$0.00,see above,--
13,Events - CT/NE,$0.00,$167.14,$309.00
14,Events - not recurring,$0.00,$316.00,"$2,920.00"
15,Matching donations (10),$0.00,$0.00,"$1,769.19"
16,Grants,$0.00,$0.00,$0.00
17,"PuraVida bracelets, Dream books, Photo sales, ...",$0.00,$0.00,"$1,021.28"
18,University Efforts,$0.00,$0.00,"$1,016.00"
19,"Amazon Smile, Cafepress, Goodshop",$0.00,$0.00,$192.33
20,Birthdays and weddings,$0.00,$0.00,"$6,049.31"
21,Events - Ecuador,$0.00,$24.14,"$1,213.60"
22,Unsolicited Gifts,$0.00,$0.00,"$30,005.66"
23,NaN,$635.06,"$4,691.33","$191,055.40"
24,Additional Expenses (not related to an advance...,NaN,$48.54,marketing
25,NaN,NaN,$50.00,CT State Reg
26,NaN,NaN,$98.54,total other fundraising expenses
27,NaN,NaN,4038.95,volunteer expenses

In [22]:
income_vs_expense = pd.merge(donation_data, expenses, how="left", on='Campaign Name')
income_vs_expense = income_vs_expense[['Bucket', 'Campaign Name', 'Expenses FY21', 'Income FY21', 'In-Kind Donations FY21', 'Volunteer Hours FY21', 'Expenses FY20', 'Funds Raised FY20', 'Income FY20', 'In-Kind Donations FY21', 'Volunteer Hours FY21']]
income_vs_expense

,Bucket,Campaign Name,Expenses FY21,Income FY21,In-Kind Donations FY21,Volunteer Hours FY21,Expenses FY20,Funds Raised FY20,Income FY20,In-Kind Donations FY21,Volunteer Hours FY21
0,1: Individual Giving,Sponsor a Scholar,$0.00,"$12,420.45",$0.00,30,$0.00,"$25,213.95","$25,213.95",$0.00,30
1,1: Individual Giving,Sponsor a Scholar - Fund a Thon,$0.00,coming soon,$0.00,coming soon,$0.00,"$3,610.00","$3,610.00",$0.00,coming soon
2,1: Individual Giving,Appeal - June,$210.06,"$9,641.00",$0.00,27,$0.00,"$25,295.00","$25,295.00",$0.00,27
3,1: Individual Giving,Appeal - December,$0.00,coming soon,$0.00,coming soon,$224.92,"$9,637.11","$9,637.11",$0.00,coming soon
4,1: Individual Giving,Online appeal - Giving Tuesday,$0.00,coming soon,$0.00,coming soon,$25.50,"$8,544.94","$8,544.94",$0.00,coming soon
5,1: Individual Giving,Online event - Starfish Search,$0.00,coming soon,$0.00,coming soon,$302.00,"$1,268.00","$1,268.00",$0.00,coming soon
6,1: Individual Giving,Online event - Starfish Bracket Challenge,$175.00,coming soon,$0.00,5,$0.00,"$1,115.00","$1,115.00",$0.00,5
7,1: Individual Giving,Lapsed Donors,$0.00,coming soon,$0.00,coming soon,$0.00,$400.00,$400.00,$0.00,coming soon
8,1: Individual Giving,Benefit dinner tickets,NaN,"$4,817.12",$384.79,538,NaN,NaN,"$4,010.00",$384.79,538
9,1: Individual Giving,Benefit dinner individual donations,NaN,"$8,250.40",$0.00,0,NaN,NaN,"$2,825.00",$0.00,0
10,1: Individual Giving,Benefit dinner auction,NaN,"$9,808.13","$9,243.06",152,NaN,NaN,"$11,491.00","$9,243.06",152
11,1: Individual Giving,Events - CT/NE,$0.00,coming soon,$0.00,coming soon,$167.14,$309.00,$309.00,$0.00,coming soon
12,1: Individual Giving,Events - not recurring,$0.00,$309.30,$0.00,0,$316.00,"$2,920.00","$2,920.00",$0.00,0
13,1: Individual Giving,Events - Ecuador,$0.00,$0.00,$0.00,0,$24.14,"$1,213.60","$1,213.60",$0.00,0
14,1: Individual Giving,Birthdays and weddings,$0.00,"$1,667.52",$0.00,3,$0.00,"$6,049.31","$6,049.31",$0.00,3
15,1: Individual Giving,Unsolicited Gifts,$0.00,"$5,178.48",$0.00,3,$0.00,"$30,005.66","$30,005.66",$0.00,3
16,2: Major Donors,Benefit dinner sponsorships (5),NaN,"$50,000.00",$0.00,57,NaN,NaN,"$87,500.00",$0.00,57
17,2: Major Donors,University Efforts,$0.00,coming soon,$0.00,1,$0.00,"$1,016.00","$1,016.00",$0.00,1
18,3: Grants,Grants,$0.00,$750.00,$0.00,6,$0.00,$0.00,$0.00,$0.00,6
19,4: Corporations,Benefit dinner sponsorships (1),NaN,$520.56,$0.00,1,NaN,NaN,$500.00,$0.00,1
20,4: Corporations,Matching donations (10),$0.00,"$2,413.26",$0.00,6,$0.00,"$1,769.19","$1,769.19",$0.00,6
21,5: Earned Revenue,Ecua vols/visitors,$0.00,$0.00,$0.00,0,$25.00,"$5,487.46","$5,487.46",$0.00,0
22,5: Earned Revenue,Benefit dinner item sales,NaN,$601.06,$704.94,11,NaN,NaN,"$1,183.00",$704.94,11
23,5: Earned Revenue,Pura Vida sales,NaN,$5.00,$0.00,1,NaN,NaN,$5.00,$0.00,1
24,5: Earned Revenue,Dream Book sales,NaN,$0.00,$0.00,1,NaN,NaN,$0.00,$0.00,1
25,5: Earned Revenue,Popsocket sales,NaN,$0.00,$0.00,1,NaN,NaN,$0.00,$0.00,1
26,5: Earned Revenue,Photo sales,NaN,$0.00,$0.00,1,NaN,NaN,$40.00,$0.00,1
27,5: Earned Revenue,Speaking events,NaN,$0.00,$0.00,0,NaN,NaN,$414.00,$0.00,0
28,5: Earned Revenue,Amazon Smile,NaN,$32.35,$0.00,1,NaN,NaN,$192.33,$0.00,1
29,5: Earned Revenue,CafePress,NaN,$0.00,$0.00,0,NaN,NaN,$0.00,$0.00,0
30,5: Earned Revenue,Goodshop,NaN,$0.00,$0.00,0,NaN,NaN,$0.00,$0.00,0
31,NaN,NaN,$635.06,NaN,NaN,NaN,"$4,691.33","$191,055.40",NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,$50.00,CT State Reg,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,$98.54,total other fundraising expenses,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,4038.95,volunteer expenses,NaN,NaN,NaN
35,No bucket,Thank-a-thon,$0.00,NaN,NaN,NaN,$386.63,--,NaN,NaN,NaN
36,No bucket,4th quarter press,--,NaN,NaN,NaN,--,--,NaN,NaN,NaN

In [23]:
income_vs_expense['Campaign Name'].value_counts()

Online event - Starfish Bracket Challenge    1
Unsolicited Gifts                            1
Lapsed Donors                                1
Benefit dinner tickets                       1
Online appeal - Giving Tuesday               1
Benefit dinner sponsorships (1)              1
Speaking events                              1
Online event - Starfish Search               1
4th quarter press                            1
Dream Book sales                             1
Appeal - June                                1
Thank-a-thon                                 1
University Efforts                           1
Events - not recurring                       1
Appeal - December                            1
CafePress                                    1
Pura Vida sales                              1
Ecua vols/visitors                           1
Benefit dinner individual donations          1
Matching donations (10)                      1
Sponsor a Scholar                            1
Sponsor a Scholar - Fund a Thon              1
Events - CT/NE                               1
Benefit dinner item sales                    1
Benefit dinner auction                       1
Events - Ecuador                             1
Popsocket sales                              1
Amazon Smile                                 1
Birthdays and weddings                       1
Grants                                       1
Benefit dinner sponsorships (5)              1
Goodshop                                     1
Photo sales                                  1
Name: Campaign Name, dtype: int64